import "./globals.css";
import Navbar from "../components/Navbar";
import TopBar from "../components/Topbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="flex flex-col md:flex-row">
          <div className="w-full md:w-1/4">
            <Navbar />
          </div>
          <div className="w-full md:w-3/4">
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
