// import Navbar from "../components/Navbar";
import './globals.css';
import React from 'react';

import TopBar from "../components/Topbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout ({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className='bg-gray_dark'>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
